nav:
    - index.md
    - asennus
    - linux
    - Peruskäyttö: peruskaytto
    - CLI: cli
    - paketinhallinta
    - prosessit
    - Etäkäyttö: etakaytto
    - 🚧 Tiedostojärjestelmä: tiedostojarjestelma
    - 🚧 C-ohjelmointi: c_ohjelmointi
    - "*"